version: '3'

services:
  postgres:
    image: postgres:latest
    # build: .
    # environment:
    #   NODE_ENV: production
    # ports:
    #   - 3000:3000
  redis:
    image: redis:latest
  server:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes: 
      - /app/node_modules
      - ./server:/app
